// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABLfcvwOYXWLTzcicPhfii0SEfI1mk5g4',
    appId: '1:907948472204:web:31938b198cc0ba343b88a9',
    messagingSenderId: '907948472204',
    projectId: 'hiram-2640f',
    authDomain: 'hiram-2640f.firebaseapp.com',
    storageBucket: 'hiram-2640f.firebasestorage.app',
    measurementId: 'G-T9210XEG7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Ghbr-UWeR5y3NJVnC6CNJZijYPDULfo',
    appId: '1:907948472204:android:a15422e7693848163b88a9',
    messagingSenderId: '907948472204',
    projectId: 'hiram-2640f',
    storageBucket: 'hiram-2640f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClsV5k2BIuIe9foydX_-yh3cNPJCdAk10',
    appId: '1:907948472204:ios:5f7eb97148a6d5ce3b88a9',
    messagingSenderId: '907948472204',
    projectId: 'hiram-2640f',
    storageBucket: 'hiram-2640f.firebasestorage.app',
    iosBundleId: 'com.example.hiram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClsV5k2BIuIe9foydX_-yh3cNPJCdAk10',
    appId: '1:907948472204:ios:5f7eb97148a6d5ce3b88a9',
    messagingSenderId: '907948472204',
    projectId: 'hiram-2640f',
    storageBucket: 'hiram-2640f.firebasestorage.app',
    iosBundleId: 'com.example.hiram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABLfcvwOYXWLTzcicPhfii0SEfI1mk5g4',
    appId: '1:907948472204:web:75652767c1d4eb993b88a9',
    messagingSenderId: '907948472204',
    projectId: 'hiram-2640f',
    authDomain: 'hiram-2640f.firebaseapp.com',
    storageBucket: 'hiram-2640f.firebasestorage.app',
    measurementId: 'G-Z2M29VWDQD',
  );
}
